version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - /
      # crates with [workspace] table are not recognized by the above 'directory: /'
      - /docker/test/fixtures/no-std-qemu
    schedule:
      interval: daily
    commit-message:
      prefix: ''
    ignore:
      # See Cargo.toml.
      - dependency-name: cc
      - dependency-name: cmake
    labels: []
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ''
    labels: []
