[package]
name = "build-libunwind"
edition = "2021"

[dependencies]
anyhow = "1"
cc = "1"
fs-err = "2"

[lints.rust]
rust_2018_idioms = "warn"
single_use_lifetimes = "warn"
unsafe_op_in_unsafe_fn = "warn"
