name: CI

permissions:
  contents: read
  packages: write

on:
  pull_request:
  push:
    branches:
      - main
      - dev
    tags:
      - '[0-9]+-[0-9]+-[0-9]+'
  schedule:
    - cron: '0 1 * * 5'
  workflow_dispatch:

jobs:
  tidy:
    uses: taiki-e/workflows/.github/workflows/tidy.yml@main

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: linux-gnu
          - target: linux-gnu
            host: aarch64
          - target: linux-musl
            musl: '1.1'
          - target: linux-musl
            musl: '1.2'
          - target: linux-uclibc
          # TODO(android): https://github.com/rust-lang/rust/issues/103673
          # - target: android
          - target: freebsd
          - target: netbsd
          - target: openbsd
          - target: dragonfly
          - target: solaris
          - target: illumos
          - target: redox
          # - target: fuchsia
          # TODO(wasi):
          # = note: clang-15: error: unsupported option '--export'
          #         clang-15: error: unsupported option '--stack-first'
          #         clang-15: error: unsupported option '--allow-undefined'
          #         clang-15: error: unsupported option '--fatal-warnings'
          #         clang-15: error: unsupported option '--no-demangle'
          #         clang-15: error: unsupported option '--gc-sections'
          #         clang-15: error: unknown argument: '-flavor'
          #         clang-15: error: no such file or directory: 'wasm'
          #         clang-15: error: no such file or directory: '__main_void'
          # - target: wasi
          - target: emscripten
          - target: windows-gnu
          - target: windows-gnu
            host: aarch64
          - target: none
          - target: none
            host: aarch64
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          driver-opts: |
            env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760
            network=host
      - run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          echo "PUSH_TO_GHCR=1" >> "${GITHUB_ENV}"
        if: github.repository_owner == 'taiki-e' && github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
      - run: tools/build-docker.sh "${{ matrix.target }}"
        env:
          HOST_ARCH: ${{ matrix.host }}
          MUSL_VERSION: ${{ matrix.musl }}

  manifest:
    if: github.repository_owner == 'taiki-e' && github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          echo "PUSH_TO_GHCR=1" >> "${GITHUB_ENV}"
        if: github.repository_owner == 'taiki-e' && github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
      - run: tools/docker-manifest.sh

  codegen:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup toolchain add nightly --no-self-update && rustup default nightly
      - run: tools/gen.sh
      - run: git add -N . && git diff --exit-code
